---
title: "mums2"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{mums2}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r setup}
library(mums2)
library(mpactr)
library(clustur)
```

# Import
```{r import_data}
example_path("squid_meta_data.csv")
squid_data <- import_data(example_path("squid_peak_table.csv"), 
  example_path("squid_meta_data.csv"), "None")
```

# Filter
```{r import_data}
  squid_filter <- squid_data  |> 
    filter_mispicked_ions(ringwin = 0.8,
      isowin = 0.01,
      trwin = 0.01,
      max_iso_shift = 3,
      merge_peaks = TRUE, 
      merge_method = "sum")
```

# Preprocess ms2 data
```{r preprocess}
  mass_data_set <- convert_mpactr_object_to_mass_data_set(squid_filter)
    mass_data_set <- massdataset::mutate_ms2(
    object = mass_data_set, 
    polarity = "negative",
    ms1.ms2.match.mz.tol = 100,
    ms1.ms2.match.rt.tol = 150
    )
```

# Normalize
```{r Normalization}
  mass_data_set <- mass_data_set %>%
    massdataset::activate_mass_dataset("expression_data") %>%
    normalize_ms("rel_abund")
  
```

# Annotations

```{r annotations}
  dir <- "exttestdata"
  file <- "demo_massdataset"
  r_file <- "database_data/PSU-MSMLS.msp"
  dat <- readRDS(test_path(dir, file))
  dat_sub_200 <- dat %>%
    massdataset::activate_mass_dataset("variable_info") %>%
    massdataset::slice_head(n = 200)

  psu_msmls <- massdatabase::read_msp_data(test_path(dir, r_file),
                                          source = "gnps")

  annotations <- annotate_ms2(mass_data_set, psu_msmls,
                              gnps_params(0.5), 2, .2)
```

# Scoring/Distance
```{r scoring}
 dist <- dist_ms2(mass_data_set, 0.3, 2, gnps_params(0.5))
```

# Omus (Clustering)
```{r omus}
sparse_matrix <- create_sparse_matrix(dist$i, dist$j, dist$dist)

  # Create Count Table 
  peak_table <- get_peak_table(squid_filter)
  count_table <- create_count_table(peak_table)

  # Create Distance Object
  dist <- read_dist(sparse_matrix, count_table, 0.3, F)

  get_distance_df(dist)

  # Cluster Data
  cluster_results <- cluster(dist, 0.2, "opticlust")


```

# Create the community object/matrix
```{r community_object}
  # Create community object
  community_matrix <- create_community_matrix(cluster_results)
  community_obj <- create_community_matrix_object(cluster_results)
```

# Run the diversity metrics
## Rarefaction
```{r diversity_metrics}
  # Rarefacton
  rarefy_new <- rarefy_ms(community_obj, 4000, 100)
  
```


## Alpha Diversity
```{r alpha_diversity}
  # Calculate Alpha Diversity
  shannon_diversity <- diversity(community_obj, "shannon")
  simpson_diversity <- diversity(community_obj, "simpson")

```

## Beta Diversity
```{r beta}
  #Calculate Beta Diversity
  braycurits <- diversity(community_obj, "bray")

```

## Average Subsampled Dissimilarity
```{r average_subsampled_dissimilarity}
  # Avg dist
  avg <- averaged_subsampled_dissimilarity(community_obj, 4000, 100, "bray", 100)
```
