test_that("test that we can create a communiy object", {
  count_table <- test_path("exttestdata", "final.count_table")
  distances <- test_path("exttestdata", "final.dist")
  final_count <- read_count(count_table)
  final_dist <- read_dist(distances, final_count, 0.03, F)
  final_cluster <- cluster(final_dist, 0.03, "opticlust")
  communiy_object <- create_community_matrix_object(final_cluster)
  expect_true("community_object" %in% class(communiy_object))
})

test_that("Test that get community object returns a community matrix", {
  count_table <- test_path("exttestdata", "final.count_table")
  distances <- test_path("exttestdata", "final.dist")
  final_count <- read_count(count_table)
  final_dist <- read_dist(distances, final_count, 0.03, F)
  final_cluster <- cluster(final_dist, 0.03, "opticlust")
  communiy_object <- create_community_matrix_object(final_cluster)
  community_matrix <- get_community_matrix(communiy_object)
  expect_true("matrix" %in% class(community_matrix))
})
test_that("Expect get_community_object and matrix to error when given the wrong object", {
  count_table <- test_path("exttestdata", "final.count_table")
  distances <- test_path("exttestdata", "final.dist")
  final_count <- read_count(count_table)
  final_dist <- read_dist(distances, final_count, 0.03, F)
  final_cluster <- cluster(final_dist, 0.03, "opticlust")
  expect_error(create_community_matrix_object(count_table))
  expect_error(get_community_matrix(count_table))
})
