test_that("We can convert community objects into distance objects", {
  dat <- readRDS(test_path("exttestdata", "matched_data.RDS"))
  distances <- dist_ms2(dat, 0.3, 2, gnps_params(0.5))
  result <- cluster_data(distances, dat,  0.3, "opticlust")
  communiy_object <- create_community_matrix_object(result)
  result <- dist_shared(communiy_object, 400, 10, "bray", 2)
  dist_obj <- community_object_to_distance_object(result)
  expect_s3_class(dist_obj, "dist")
  expect_true(length(dist_obj) == 210)
})
