test_that("cluster_data works as expected", {
  peak_table <- test_path("exttestdata", "peak_table.csv")
  meta_data <- test_path("exttestdata", "meta_data.csv")
  mpact_data <- import_data(peak_table, meta_data, "Progenesis")
  mass_data_set <- readRDS(test_path("exttestdata", "test_mass_data_set.RDS"))
  distances <- dist_ms2(mass_data_set, 0.3, 2, gnps_params(0.5))
  results <- cluster_data(distances, get_peak_table(mpact_data), "opticlust")
  expect_true(nrow(results$abundance) == 17370)
  expect_true(ncol(results$abundance) == 3)
  expect_true(length(results) == 5)
})
