// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// AnnotateMs2Features
Rcpp::DataFrame AnnotateMs2Features(const std::vector<std::string>& variableId, const std::vector<std::string>& ms2Id, const std::vector<float>& ms2Mz, const std::vector<float>& ms2Rt, const Rcpp::List& ms2Spectra, const Rcpp::List& reference, const Rcpp::List& parameters, const double precursorThreshold, double minScore);
RcppExport SEXP _mums2_AnnotateMs2Features(SEXP variableIdSEXP, SEXP ms2IdSEXP, SEXP ms2MzSEXP, SEXP ms2RtSEXP, SEXP ms2SpectraSEXP, SEXP referenceSEXP, SEXP parametersSEXP, SEXP precursorThresholdSEXP, SEXP minScoreSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type variableId(variableIdSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type ms2Id(ms2IdSEXP);
    Rcpp::traits::input_parameter< const std::vector<float>& >::type ms2Mz(ms2MzSEXP);
    Rcpp::traits::input_parameter< const std::vector<float>& >::type ms2Rt(ms2RtSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type ms2Spectra(ms2SpectraSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type reference(referenceSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const double >::type precursorThreshold(precursorThresholdSEXP);
    Rcpp::traits::input_parameter< double >::type minScore(minScoreSEXP);
    rcpp_result_gen = Rcpp::wrap(AnnotateMs2Features(variableId, ms2Id, ms2Mz, ms2Rt, ms2Spectra, reference, parameters, precursorThreshold, minScore));
    return rcpp_result_gen;
END_RCPP
}
// distMS2
Rcpp::DataFrame distMS2(const Rcpp::List spectraDataList, const Rcpp::List parameters, double precursor_thresh, double cutoff);
RcppExport SEXP _mums2_distMS2(SEXP spectraDataListSEXP, SEXP parametersSEXP, SEXP precursor_threshSEXP, SEXP cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type spectraDataList(spectraDataListSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< double >::type precursor_thresh(precursor_threshSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(distMS2(spectraDataList, parameters, precursor_thresh, cutoff));
    return rcpp_result_gen;
END_RCPP
}
// CalculateDiversityCommunityObject
Rcpp::NumericMatrix CalculateDiversityCommunityObject(const SEXP& communityMatrix, const std::string& diversityIndex);
RcppExport SEXP _mums2_CalculateDiversityCommunityObject(SEXP communityMatrixSEXP, SEXP diversityIndexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type communityMatrix(communityMatrixSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type diversityIndex(diversityIndexSEXP);
    rcpp_result_gen = Rcpp::wrap(CalculateDiversityCommunityObject(communityMatrix, diversityIndex));
    return rcpp_result_gen;
END_RCPP
}
// CreateCommunityMatrix
SEXP CreateCommunityMatrix(Rcpp::NumericMatrix communityMatrix);
RcppExport SEXP _mums2_CreateCommunityMatrix(SEXP communityMatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type communityMatrix(communityMatrixSEXP);
    rcpp_result_gen = Rcpp::wrap(CreateCommunityMatrix(communityMatrix));
    return rcpp_result_gen;
END_RCPP
}
// GetCommunityMatrix
SEXP GetCommunityMatrix(SEXP communityMatrix);
RcppExport SEXP _mums2_GetCommunityMatrix(SEXP communityMatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type communityMatrix(communityMatrixSEXP);
    rcpp_result_gen = Rcpp::wrap(GetCommunityMatrix(communityMatrix));
    return rcpp_result_gen;
END_RCPP
}
// RarefactionCalculation
Rcpp::NumericMatrix RarefactionCalculation(const SEXP& communityMatrix, const int64_t size, const int64_t threshold);
RcppExport SEXP _mums2_RarefactionCalculation(SEXP communityMatrixSEXP, SEXP sizeSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type communityMatrix(communityMatrixSEXP);
    Rcpp::traits::input_parameter< const int64_t >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< const int64_t >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(RarefactionCalculation(communityMatrix, size, threshold));
    return rcpp_result_gen;
END_RCPP
}
// FasterAvgDist
Rcpp::NumericMatrix FasterAvgDist(const SEXP& communityMatrix, const std::string& index, const int64_t size, const int64_t threshold, const int iterations);
RcppExport SEXP _mums2_FasterAvgDist(SEXP communityMatrixSEXP, SEXP indexSEXP, SEXP sizeSEXP, SEXP thresholdSEXP, SEXP iterationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type communityMatrix(communityMatrixSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type index(indexSEXP);
    Rcpp::traits::input_parameter< const int64_t >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< const int64_t >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< const int >::type iterations(iterationsSEXP);
    rcpp_result_gen = Rcpp::wrap(FasterAvgDist(communityMatrix, index, size, threshold, iterations));
    return rcpp_result_gen;
END_RCPP
}
// squareRootNormalize
std::vector<double> squareRootNormalize(std::vector<double>& vec);
RcppExport SEXP _mums2_squareRootNormalize(SEXP vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double>& >::type vec(vecSEXP);
    rcpp_result_gen = Rcpp::wrap(squareRootNormalize(vec));
    return rcpp_result_gen;
END_RCPP
}
// scaleNormalize
std::vector<double> scaleNormalize(std::vector<double>& vec);
RcppExport SEXP _mums2_scaleNormalize(SEXP vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double>& >::type vec(vecSEXP);
    rcpp_result_gen = Rcpp::wrap(scaleNormalize(vec));
    return rcpp_result_gen;
END_RCPP
}
// ScoreMs2
double ScoreMs2(std::string name1, std::vector<double> mz1, std::vector<double> intensity1, double precursorMz1, std::string name2, std::vector<double> mz2, std::vector<double> intensity2, double precursorMz2, Rcpp::List parameters);
RcppExport SEXP _mums2_ScoreMs2(SEXP name1SEXP, SEXP mz1SEXP, SEXP intensity1SEXP, SEXP precursorMz1SEXP, SEXP name2SEXP, SEXP mz2SEXP, SEXP intensity2SEXP, SEXP precursorMz2SEXP, SEXP parametersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type name1(name1SEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type mz1(mz1SEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type intensity1(intensity1SEXP);
    Rcpp::traits::input_parameter< double >::type precursorMz1(precursorMz1SEXP);
    Rcpp::traits::input_parameter< std::string >::type name2(name2SEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type mz2(mz2SEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type intensity2(intensity2SEXP);
    Rcpp::traits::input_parameter< double >::type precursorMz2(precursorMz2SEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type parameters(parametersSEXP);
    rcpp_result_gen = Rcpp::wrap(ScoreMs2(name1, mz1, intensity1, precursorMz1, name2, mz2, intensity2, precursorMz2, parameters));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP run_testthat_tests(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_mums2_AnnotateMs2Features", (DL_FUNC) &_mums2_AnnotateMs2Features, 9},
    {"_mums2_distMS2", (DL_FUNC) &_mums2_distMS2, 4},
    {"_mums2_CalculateDiversityCommunityObject", (DL_FUNC) &_mums2_CalculateDiversityCommunityObject, 2},
    {"_mums2_CreateCommunityMatrix", (DL_FUNC) &_mums2_CreateCommunityMatrix, 1},
    {"_mums2_GetCommunityMatrix", (DL_FUNC) &_mums2_GetCommunityMatrix, 1},
    {"_mums2_RarefactionCalculation", (DL_FUNC) &_mums2_RarefactionCalculation, 3},
    {"_mums2_FasterAvgDist", (DL_FUNC) &_mums2_FasterAvgDist, 5},
    {"_mums2_squareRootNormalize", (DL_FUNC) &_mums2_squareRootNormalize, 1},
    {"_mums2_scaleNormalize", (DL_FUNC) &_mums2_scaleNormalize, 1},
    {"_mums2_ScoreMs2", (DL_FUNC) &_mums2_ScoreMs2, 9},
    {"run_testthat_tests", (DL_FUNC) &run_testthat_tests, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_mums2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
