// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppThread.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// AnnotateMs2Features
Rcpp::DataFrame AnnotateMs2Features(const Rcpp::DataFrame& queryList, const Rcpp::List querySpectra, const Rcpp::List referenceList, const Rcpp::List& scoringParameters, const Rcpp::StringVector& formulas, const double precursorThreshold, const double minScoreThreshold, const double chemicalMinScore, const size_t minPeaks);
RcppExport SEXP _mums2_AnnotateMs2Features(SEXP queryListSEXP, SEXP querySpectraSEXP, SEXP referenceListSEXP, SEXP scoringParametersSEXP, SEXP formulasSEXP, SEXP precursorThresholdSEXP, SEXP minScoreThresholdSEXP, SEXP chemicalMinScoreSEXP, SEXP minPeaksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type queryList(queryListSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type querySpectra(querySpectraSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type referenceList(referenceListSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type scoringParameters(scoringParametersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::StringVector& >::type formulas(formulasSEXP);
    Rcpp::traits::input_parameter< const double >::type precursorThreshold(precursorThresholdSEXP);
    Rcpp::traits::input_parameter< const double >::type minScoreThreshold(minScoreThresholdSEXP);
    Rcpp::traits::input_parameter< const double >::type chemicalMinScore(chemicalMinScoreSEXP);
    Rcpp::traits::input_parameter< const size_t >::type minPeaks(minPeaksSEXP);
    rcpp_result_gen = Rcpp::wrap(AnnotateMs2Features(queryList, querySpectra, referenceList, scoringParameters, formulas, precursorThreshold, minScoreThreshold, chemicalMinScore, minPeaks));
    return rcpp_result_gen;
END_RCPP
}
// distMS2
Rcpp::DataFrame distMS2(const Rcpp::List spectraDataList, const Rcpp::List parameters, const double precursor_thresh, const double cutoff, const int minPeaks);
RcppExport SEXP _mums2_distMS2(SEXP spectraDataListSEXP, SEXP parametersSEXP, SEXP precursor_threshSEXP, SEXP cutoffSEXP, SEXP minPeaksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type spectraDataList(spectraDataListSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const double >::type precursor_thresh(precursor_threshSEXP);
    Rcpp::traits::input_parameter< const double >::type cutoff(cutoffSEXP);
    Rcpp::traits::input_parameter< const int >::type minPeaks(minPeaksSEXP);
    rcpp_result_gen = Rcpp::wrap(distMS2(spectraDataList, parameters, precursor_thresh, cutoff, minPeaks));
    return rcpp_result_gen;
END_RCPP
}
// CalculateDiversityCommunityObject
Rcpp::NumericMatrix CalculateDiversityCommunityObject(const SEXP& communityMatrix, const std::string& diversityIndex);
RcppExport SEXP _mums2_CalculateDiversityCommunityObject(SEXP communityMatrixSEXP, SEXP diversityIndexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type communityMatrix(communityMatrixSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type diversityIndex(diversityIndexSEXP);
    rcpp_result_gen = Rcpp::wrap(CalculateDiversityCommunityObject(communityMatrix, diversityIndex));
    return rcpp_result_gen;
END_RCPP
}
// CreateCommunityMatrix
SEXP CreateCommunityMatrix(Rcpp::NumericMatrix communityMatrix);
RcppExport SEXP _mums2_CreateCommunityMatrix(SEXP communityMatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type communityMatrix(communityMatrixSEXP);
    rcpp_result_gen = Rcpp::wrap(CreateCommunityMatrix(communityMatrix));
    return rcpp_result_gen;
END_RCPP
}
// GetCommunityMatrix
SEXP GetCommunityMatrix(SEXP communityMatrix);
RcppExport SEXP _mums2_GetCommunityMatrix(SEXP communityMatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type communityMatrix(communityMatrixSEXP);
    rcpp_result_gen = Rcpp::wrap(GetCommunityMatrix(communityMatrix));
    return rcpp_result_gen;
END_RCPP
}
// RarefactionCalculation
Rcpp::NumericMatrix RarefactionCalculation(const SEXP& communityMatrix, const uint32_t size, const uint32_t threshold, const int numOfThreads);
RcppExport SEXP _mums2_RarefactionCalculation(SEXP communityMatrixSEXP, SEXP sizeSEXP, SEXP thresholdSEXP, SEXP numOfThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type communityMatrix(communityMatrixSEXP);
    Rcpp::traits::input_parameter< const uint32_t >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< const uint32_t >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< const int >::type numOfThreads(numOfThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(RarefactionCalculation(communityMatrix, size, threshold, numOfThreads));
    return rcpp_result_gen;
END_RCPP
}
// FasterAvgDist
Rcpp::DataFrame FasterAvgDist(const SEXP& communityMatrix, const std::string& index, const uint32_t size, const uint32_t threshold, const bool subsample, const int numOfThreads, const int iterations);
RcppExport SEXP _mums2_FasterAvgDist(SEXP communityMatrixSEXP, SEXP indexSEXP, SEXP sizeSEXP, SEXP thresholdSEXP, SEXP subsampleSEXP, SEXP numOfThreadsSEXP, SEXP iterationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type communityMatrix(communityMatrixSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type index(indexSEXP);
    Rcpp::traits::input_parameter< const uint32_t >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< const uint32_t >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< const bool >::type subsample(subsampleSEXP);
    Rcpp::traits::input_parameter< const int >::type numOfThreads(numOfThreadsSEXP);
    Rcpp::traits::input_parameter< const int >::type iterations(iterationsSEXP);
    rcpp_result_gen = Rcpp::wrap(FasterAvgDist(communityMatrix, index, size, threshold, subsample, numOfThreads, iterations));
    return rcpp_result_gen;
END_RCPP
}
// ReadMgf
Rcpp::List ReadMgf(const std::string& path);
RcppExport SEXP _mums2_ReadMgf(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(ReadMgf(path));
    return rcpp_result_gen;
END_RCPP
}
// ReadMsp
Rcpp::List ReadMsp(const std::string& path);
RcppExport SEXP _mums2_ReadMsp(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(ReadMsp(path));
    return rcpp_result_gen;
END_RCPP
}
// CompareMS2Ms1
Rcpp::NumericVector CompareMS2Ms1(const Rcpp::NumericVector& mz2, const Rcpp::NumericVector& mz1, const Rcpp::NumericVector& rt2, const Rcpp::NumericVector& rt1, const double mzThreshold, const double rtThreshold);
RcppExport SEXP _mums2_CompareMS2Ms1(SEXP mz2SEXP, SEXP mz1SEXP, SEXP rt2SEXP, SEXP rt1SEXP, SEXP mzThresholdSEXP, SEXP rtThresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type mz2(mz2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type mz1(mz1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type rt2(rt2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type rt1(rt1SEXP);
    Rcpp::traits::input_parameter< const double >::type mzThreshold(mzThresholdSEXP);
    Rcpp::traits::input_parameter< const double >::type rtThreshold(rtThresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(CompareMS2Ms1(mz2, mz1, rt2, rt1, mzThreshold, rtThreshold));
    return rcpp_result_gen;
END_RCPP
}
// ComputeFragmentationTree
std::string ComputeFragmentationTree(const Rcpp::List& molecularFormulas, const double parentMass, const int numberOfThreads);
RcppExport SEXP _mums2_ComputeFragmentationTree(SEXP molecularFormulasSEXP, SEXP parentMassSEXP, SEXP numberOfThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type molecularFormulas(molecularFormulasSEXP);
    Rcpp::traits::input_parameter< const double >::type parentMass(parentMassSEXP);
    Rcpp::traits::input_parameter< const int >::type numberOfThreads(numberOfThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(ComputeFragmentationTree(molecularFormulas, parentMass, numberOfThreads));
    return rcpp_result_gen;
END_RCPP
}
// squareRootNormalize
std::vector<double> squareRootNormalize(std::vector<double>& vec);
RcppExport SEXP _mums2_squareRootNormalize(SEXP vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double>& >::type vec(vecSEXP);
    rcpp_result_gen = Rcpp::wrap(squareRootNormalize(vec));
    return rcpp_result_gen;
END_RCPP
}
// scaleNormalize
std::vector<double> scaleNormalize(std::vector<double>& vec);
RcppExport SEXP _mums2_scaleNormalize(SEXP vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double>& >::type vec(vecSEXP);
    rcpp_result_gen = Rcpp::wrap(scaleNormalize(vec));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP run_testthat_tests(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_mums2_AnnotateMs2Features", (DL_FUNC) &_mums2_AnnotateMs2Features, 9},
    {"_mums2_distMS2", (DL_FUNC) &_mums2_distMS2, 5},
    {"_mums2_CalculateDiversityCommunityObject", (DL_FUNC) &_mums2_CalculateDiversityCommunityObject, 2},
    {"_mums2_CreateCommunityMatrix", (DL_FUNC) &_mums2_CreateCommunityMatrix, 1},
    {"_mums2_GetCommunityMatrix", (DL_FUNC) &_mums2_GetCommunityMatrix, 1},
    {"_mums2_RarefactionCalculation", (DL_FUNC) &_mums2_RarefactionCalculation, 4},
    {"_mums2_FasterAvgDist", (DL_FUNC) &_mums2_FasterAvgDist, 7},
    {"_mums2_ReadMgf", (DL_FUNC) &_mums2_ReadMgf, 1},
    {"_mums2_ReadMsp", (DL_FUNC) &_mums2_ReadMsp, 1},
    {"_mums2_CompareMS2Ms1", (DL_FUNC) &_mums2_CompareMS2Ms1, 6},
    {"_mums2_ComputeFragmentationTree", (DL_FUNC) &_mums2_ComputeFragmentationTree, 3},
    {"_mums2_squareRootNormalize", (DL_FUNC) &_mums2_squareRootNormalize, 1},
    {"_mums2_scaleNormalize", (DL_FUNC) &_mums2_scaleNormalize, 1},
    {"run_testthat_tests", (DL_FUNC) &run_testthat_tests, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_mums2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
