// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppThread.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// AnnotateMs2Features
Rcpp::DataFrame AnnotateMs2Features(const Rcpp::DataFrame& queryList, const Rcpp::List querySpectra, const SEXP annotationController, const Rcpp::List& scoringParameters, const Rcpp::StringVector& formulas, const double precursorThreshold, const double minScoreThreshold, const double chemicalMinScore, const size_t minPeaks, const int threadCount);
RcppExport SEXP _mums2_AnnotateMs2Features(SEXP queryListSEXP, SEXP querySpectraSEXP, SEXP annotationControllerSEXP, SEXP scoringParametersSEXP, SEXP formulasSEXP, SEXP precursorThresholdSEXP, SEXP minScoreThresholdSEXP, SEXP chemicalMinScoreSEXP, SEXP minPeaksSEXP, SEXP threadCountSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type queryList(queryListSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type querySpectra(querySpectraSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type annotationController(annotationControllerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type scoringParameters(scoringParametersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::StringVector& >::type formulas(formulasSEXP);
    Rcpp::traits::input_parameter< const double >::type precursorThreshold(precursorThresholdSEXP);
    Rcpp::traits::input_parameter< const double >::type minScoreThreshold(minScoreThresholdSEXP);
    Rcpp::traits::input_parameter< const double >::type chemicalMinScore(chemicalMinScoreSEXP);
    Rcpp::traits::input_parameter< const size_t >::type minPeaks(minPeaksSEXP);
    Rcpp::traits::input_parameter< const int >::type threadCount(threadCountSEXP);
    rcpp_result_gen = Rcpp::wrap(AnnotateMs2Features(queryList, querySpectra, annotationController, scoringParameters, formulas, precursorThreshold, minScoreThreshold, chemicalMinScore, minPeaks, threadCount));
    return rcpp_result_gen;
END_RCPP
}
// distMS2
Rcpp::DataFrame distMS2(const Rcpp::List spectraDataList, const Rcpp::List parameters, const double precursor_thresh, const double cutoff, const int minPeaks, const int numberOfThreads);
RcppExport SEXP _mums2_distMS2(SEXP spectraDataListSEXP, SEXP parametersSEXP, SEXP precursor_threshSEXP, SEXP cutoffSEXP, SEXP minPeaksSEXP, SEXP numberOfThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type spectraDataList(spectraDataListSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const double >::type precursor_thresh(precursor_threshSEXP);
    Rcpp::traits::input_parameter< const double >::type cutoff(cutoffSEXP);
    Rcpp::traits::input_parameter< const int >::type minPeaks(minPeaksSEXP);
    Rcpp::traits::input_parameter< const int >::type numberOfThreads(numberOfThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(distMS2(spectraDataList, parameters, precursor_thresh, cutoff, minPeaks, numberOfThreads));
    return rcpp_result_gen;
END_RCPP
}
// CreateCommunityMatrix
SEXP CreateCommunityMatrix(Rcpp::NumericMatrix communityMatrix);
RcppExport SEXP _mums2_CreateCommunityMatrix(SEXP communityMatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type communityMatrix(communityMatrixSEXP);
    rcpp_result_gen = Rcpp::wrap(CreateCommunityMatrix(communityMatrix));
    return rcpp_result_gen;
END_RCPP
}
// GetCommunityMatrix
SEXP GetCommunityMatrix(SEXP communityMatrix);
RcppExport SEXP _mums2_GetCommunityMatrix(SEXP communityMatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type communityMatrix(communityMatrixSEXP);
    rcpp_result_gen = Rcpp::wrap(GetCommunityMatrix(communityMatrix));
    return rcpp_result_gen;
END_RCPP
}
// RarefactionCalculation
Rcpp::NumericMatrix RarefactionCalculation(const SEXP& communityMatrix, const uint64_t size, const uint64_t threshold, const int numberOfThreads, const int seed);
RcppExport SEXP _mums2_RarefactionCalculation(SEXP communityMatrixSEXP, SEXP sizeSEXP, SEXP thresholdSEXP, SEXP numberOfThreadsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type communityMatrix(communityMatrixSEXP);
    Rcpp::traits::input_parameter< const uint64_t >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< const uint64_t >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< const int >::type numberOfThreads(numberOfThreadsSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(RarefactionCalculation(communityMatrix, size, threshold, numberOfThreads, seed));
    return rcpp_result_gen;
END_RCPP
}
// FasterAvgDist
Rcpp::NumericMatrix FasterAvgDist(const SEXP& communityMatrix, const std::string& index, const uint64_t size, const uint64_t threshold, const bool subsample, const int numberOfThreads, const int iterations, const int seed);
RcppExport SEXP _mums2_FasterAvgDist(SEXP communityMatrixSEXP, SEXP indexSEXP, SEXP sizeSEXP, SEXP thresholdSEXP, SEXP subsampleSEXP, SEXP numberOfThreadsSEXP, SEXP iterationsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type communityMatrix(communityMatrixSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type index(indexSEXP);
    Rcpp::traits::input_parameter< const uint64_t >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< const uint64_t >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< const bool >::type subsample(subsampleSEXP);
    Rcpp::traits::input_parameter< const int >::type numberOfThreads(numberOfThreadsSEXP);
    Rcpp::traits::input_parameter< const int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(FasterAvgDist(communityMatrix, index, size, threshold, subsample, numberOfThreads, iterations, seed));
    return rcpp_result_gen;
END_RCPP
}
// ReadMgf
Rcpp::List ReadMgf(const std::string& path);
RcppExport SEXP _mums2_ReadMgf(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(ReadMgf(path));
    return rcpp_result_gen;
END_RCPP
}
// ReadMsp
SEXP ReadMsp(const std::string& path);
RcppExport SEXP _mums2_ReadMsp(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(ReadMsp(path));
    return rcpp_result_gen;
END_RCPP
}
// GetNodeCount
size_t GetNodeCount(const SEXP& annotationController);
RcppExport SEXP _mums2_GetNodeCount(SEXP annotationControllerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type annotationController(annotationControllerSEXP);
    rcpp_result_gen = Rcpp::wrap(GetNodeCount(annotationController));
    return rcpp_result_gen;
END_RCPP
}
// GetNode
SEXP GetNode(const SEXP& annotationController, const int index);
RcppExport SEXP _mums2_GetNode(SEXP annotationControllerSEXP, SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type annotationController(annotationControllerSEXP);
    Rcpp::traits::input_parameter< const int >::type index(indexSEXP);
    rcpp_result_gen = Rcpp::wrap(GetNode(annotationController, index));
    return rcpp_result_gen;
END_RCPP
}
// AddOtherDatabase
SEXP AddOtherDatabase(SEXP& annotationController, SEXP& otherAnnotationController);
RcppExport SEXP _mums2_AddOtherDatabase(SEXP annotationControllerSEXP, SEXP otherAnnotationControllerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP& >::type annotationController(annotationControllerSEXP);
    Rcpp::traits::input_parameter< SEXP& >::type otherAnnotationController(otherAnnotationControllerSEXP);
    rcpp_result_gen = Rcpp::wrap(AddOtherDatabase(annotationController, otherAnnotationController));
    return rcpp_result_gen;
END_RCPP
}
// CompareMS2Ms1
Rcpp::NumericVector CompareMS2Ms1(const Rcpp::NumericVector& mz2, const Rcpp::NumericVector& mz1, const Rcpp::NumericVector& rt2, const Rcpp::NumericVector& rt1, const double mzThreshold, const double rtThreshold);
RcppExport SEXP _mums2_CompareMS2Ms1(SEXP mz2SEXP, SEXP mz1SEXP, SEXP rt2SEXP, SEXP rt1SEXP, SEXP mzThresholdSEXP, SEXP rtThresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type mz2(mz2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type mz1(mz1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type rt2(rt2SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type rt1(rt1SEXP);
    Rcpp::traits::input_parameter< const double >::type mzThreshold(mzThresholdSEXP);
    Rcpp::traits::input_parameter< const double >::type rtThreshold(rtThresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(CompareMS2Ms1(mz2, mz1, rt2, rt1, mzThreshold, rtThreshold));
    return rcpp_result_gen;
END_RCPP
}
// ComputeFragmentationTree
std::string ComputeFragmentationTree(const Rcpp::List& molecularFormulas, const double parentMass, const int numberOfThreads);
RcppExport SEXP _mums2_ComputeFragmentationTree(SEXP molecularFormulasSEXP, SEXP parentMassSEXP, SEXP numberOfThreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type molecularFormulas(molecularFormulasSEXP);
    Rcpp::traits::input_parameter< const double >::type parentMass(parentMassSEXP);
    Rcpp::traits::input_parameter< const int >::type numberOfThreads(numberOfThreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(ComputeFragmentationTree(molecularFormulas, parentMass, numberOfThreads));
    return rcpp_result_gen;
END_RCPP
}
// CreateProgressBarObject
SEXP CreateProgressBarObject();
RcppExport SEXP _mums2_CreateProgressBarObject() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(CreateProgressBarObject());
    return rcpp_result_gen;
END_RCPP
}
// IncrementProgressBar
void IncrementProgressBar(SEXP& progressBar, const float progress);
RcppExport SEXP _mums2_IncrementProgressBar(SEXP progressBarSEXP, SEXP progressSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP& >::type progressBar(progressBarSEXP);
    Rcpp::traits::input_parameter< const float >::type progress(progressSEXP);
    IncrementProgressBar(progressBar, progress);
    return R_NilValue;
END_RCPP
}
// DestroyProgressBar
void DestroyProgressBar(SEXP& progressBar);
RcppExport SEXP _mums2_DestroyProgressBar(SEXP progressBarSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP& >::type progressBar(progressBarSEXP);
    DestroyProgressBar(progressBar);
    return R_NilValue;
END_RCPP
}
// TestSimilarity
std::vector<double> TestSimilarity(const std::vector<double>& mzOne, std::vector<double>& intOne, const std::vector<double>& mzTwo, std::vector<double>& intTwo, Rcpp::List scoringParamsSpectral, Rcpp::List ScoringParamsCosine, const double shift);
RcppExport SEXP _mums2_TestSimilarity(SEXP mzOneSEXP, SEXP intOneSEXP, SEXP mzTwoSEXP, SEXP intTwoSEXP, SEXP scoringParamsSpectralSEXP, SEXP ScoringParamsCosineSEXP, SEXP shiftSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<double>& >::type mzOne(mzOneSEXP);
    Rcpp::traits::input_parameter< std::vector<double>& >::type intOne(intOneSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type mzTwo(mzTwoSEXP);
    Rcpp::traits::input_parameter< std::vector<double>& >::type intTwo(intTwoSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type scoringParamsSpectral(scoringParamsSpectralSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type ScoringParamsCosine(ScoringParamsCosineSEXP);
    Rcpp::traits::input_parameter< const double >::type shift(shiftSEXP);
    rcpp_result_gen = Rcpp::wrap(TestSimilarity(mzOne, intOne, mzTwo, intTwo, scoringParamsSpectral, ScoringParamsCosine, shift));
    return rcpp_result_gen;
END_RCPP
}
// DistanceToPhylipFile
void DistanceToPhylipFile(const Rcpp::NumericMatrix& mat, const std::vector<std::string>& names, const std::string& fileName);
RcppExport SEXP _mums2_DistanceToPhylipFile(SEXP matSEXP, SEXP namesSEXP, SEXP fileNameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type names(namesSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type fileName(fileNameSEXP);
    DistanceToPhylipFile(mat, names, fileName);
    return R_NilValue;
END_RCPP
}
// DistanceDataFrameToMatrix
Rcpp::List DistanceDataFrameToMatrix(const Rcpp::DataFrame& distanceDataFrame);
RcppExport SEXP _mums2_DistanceDataFrameToMatrix(SEXP distanceDataFrameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type distanceDataFrame(distanceDataFrameSEXP);
    rcpp_result_gen = Rcpp::wrap(DistanceDataFrameToMatrix(distanceDataFrame));
    return rcpp_result_gen;
END_RCPP
}
// ToColumnFile
void ToColumnFile(const Rcpp::DataFrame& matrix, const std::vector<std::string>& names, const std::string& fileName);
RcppExport SEXP _mums2_ToColumnFile(SEXP matrixSEXP, SEXP namesSEXP, SEXP fileNameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type matrix(matrixSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type names(namesSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type fileName(fileNameSEXP);
    ToColumnFile(matrix, names, fileName);
    return R_NilValue;
END_RCPP
}
// CreateHumanMetabolomicsDB
SEXP CreateHumanMetabolomicsDB();
RcppExport SEXP _mums2_CreateHumanMetabolomicsDB() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(CreateHumanMetabolomicsDB());
    return rcpp_result_gen;
END_RCPP
}
// AddHumanMetabolomicNode
void AddHumanMetabolomicNode(SEXP& hmdbPtr, const std::vector<std::string>& names, const std::vector<std::string>& values);
RcppExport SEXP _mums2_AddHumanMetabolomicNode(SEXP hmdbPtrSEXP, SEXP namesSEXP, SEXP valuesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP& >::type hmdbPtr(hmdbPtrSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type names(namesSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type values(valuesSEXP);
    AddHumanMetabolomicNode(hmdbPtr, names, values);
    return R_NilValue;
END_RCPP
}
// PrintHMDBNames
void PrintHMDBNames(const SEXP& hmdbPtr);
RcppExport SEXP _mums2_PrintHMDBNames(SEXP hmdbPtrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type hmdbPtr(hmdbPtrSEXP);
    PrintHMDBNames(hmdbPtr);
    return R_NilValue;
END_RCPP
}
// AddSpectra
void AddSpectra(SEXP& hmdbPtr, const std::vector<std::string>& fileNames, const std::vector<std::string>& databaseNames);
RcppExport SEXP _mums2_AddSpectra(SEXP hmdbPtrSEXP, SEXP fileNamesSEXP, SEXP databaseNamesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP& >::type hmdbPtr(hmdbPtrSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type fileNames(fileNamesSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type databaseNames(databaseNamesSEXP);
    AddSpectra(hmdbPtr, fileNames, databaseNames);
    return R_NilValue;
END_RCPP
}
// ProcessMs2Files
void ProcessMs2Files(SEXP& hmdbPtr);
RcppExport SEXP _mums2_ProcessMs2Files(SEXP hmdbPtrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP& >::type hmdbPtr(hmdbPtrSEXP);
    ProcessMs2Files(hmdbPtr);
    return R_NilValue;
END_RCPP
}
// CreateAnnotationController
SEXP CreateAnnotationController(SEXP& hmdbPtr);
RcppExport SEXP _mums2_CreateAnnotationController(SEXP hmdbPtrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP& >::type hmdbPtr(hmdbPtrSEXP);
    rcpp_result_gen = Rcpp::wrap(CreateAnnotationController(hmdbPtr));
    return rcpp_result_gen;
END_RCPP
}
// ReadSpectraFile
void ReadSpectraFile(const std::string& filePath);
RcppExport SEXP _mums2_ReadSpectraFile(SEXP filePathSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type filePath(filePathSEXP);
    ReadSpectraFile(filePath);
    return R_NilValue;
END_RCPP
}
// squareRootNormalize
std::vector<double> squareRootNormalize(std::vector<double>& vec);
RcppExport SEXP _mums2_squareRootNormalize(SEXP vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double>& >::type vec(vecSEXP);
    rcpp_result_gen = Rcpp::wrap(squareRootNormalize(vec));
    return rcpp_result_gen;
END_RCPP
}
// scaleNormalize
std::vector<double> scaleNormalize(std::vector<double>& vec);
RcppExport SEXP _mums2_scaleNormalize(SEXP vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double>& >::type vec(vecSEXP);
    rcpp_result_gen = Rcpp::wrap(scaleNormalize(vec));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP run_testthat_tests(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_mums2_AnnotateMs2Features", (DL_FUNC) &_mums2_AnnotateMs2Features, 10},
    {"_mums2_distMS2", (DL_FUNC) &_mums2_distMS2, 6},
    {"_mums2_CreateCommunityMatrix", (DL_FUNC) &_mums2_CreateCommunityMatrix, 1},
    {"_mums2_GetCommunityMatrix", (DL_FUNC) &_mums2_GetCommunityMatrix, 1},
    {"_mums2_RarefactionCalculation", (DL_FUNC) &_mums2_RarefactionCalculation, 5},
    {"_mums2_FasterAvgDist", (DL_FUNC) &_mums2_FasterAvgDist, 8},
    {"_mums2_ReadMgf", (DL_FUNC) &_mums2_ReadMgf, 1},
    {"_mums2_ReadMsp", (DL_FUNC) &_mums2_ReadMsp, 1},
    {"_mums2_GetNodeCount", (DL_FUNC) &_mums2_GetNodeCount, 1},
    {"_mums2_GetNode", (DL_FUNC) &_mums2_GetNode, 2},
    {"_mums2_AddOtherDatabase", (DL_FUNC) &_mums2_AddOtherDatabase, 2},
    {"_mums2_CompareMS2Ms1", (DL_FUNC) &_mums2_CompareMS2Ms1, 6},
    {"_mums2_ComputeFragmentationTree", (DL_FUNC) &_mums2_ComputeFragmentationTree, 3},
    {"_mums2_CreateProgressBarObject", (DL_FUNC) &_mums2_CreateProgressBarObject, 0},
    {"_mums2_IncrementProgressBar", (DL_FUNC) &_mums2_IncrementProgressBar, 2},
    {"_mums2_DestroyProgressBar", (DL_FUNC) &_mums2_DestroyProgressBar, 1},
    {"_mums2_TestSimilarity", (DL_FUNC) &_mums2_TestSimilarity, 7},
    {"_mums2_DistanceToPhylipFile", (DL_FUNC) &_mums2_DistanceToPhylipFile, 3},
    {"_mums2_DistanceDataFrameToMatrix", (DL_FUNC) &_mums2_DistanceDataFrameToMatrix, 1},
    {"_mums2_ToColumnFile", (DL_FUNC) &_mums2_ToColumnFile, 3},
    {"_mums2_CreateHumanMetabolomicsDB", (DL_FUNC) &_mums2_CreateHumanMetabolomicsDB, 0},
    {"_mums2_AddHumanMetabolomicNode", (DL_FUNC) &_mums2_AddHumanMetabolomicNode, 3},
    {"_mums2_PrintHMDBNames", (DL_FUNC) &_mums2_PrintHMDBNames, 1},
    {"_mums2_AddSpectra", (DL_FUNC) &_mums2_AddSpectra, 3},
    {"_mums2_ProcessMs2Files", (DL_FUNC) &_mums2_ProcessMs2Files, 1},
    {"_mums2_CreateAnnotationController", (DL_FUNC) &_mums2_CreateAnnotationController, 1},
    {"_mums2_ReadSpectraFile", (DL_FUNC) &_mums2_ReadSpectraFile, 1},
    {"_mums2_squareRootNormalize", (DL_FUNC) &_mums2_squareRootNormalize, 1},
    {"_mums2_scaleNormalize", (DL_FUNC) &_mums2_scaleNormalize, 1},
    {"run_testthat_tests", (DL_FUNC) &run_testthat_tests, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_mums2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
