#' Annotate LC-MS/MS features
#' @description
#' Annotate query LC-MS/MS features in a `mass_data` object given a
#' reference list.
#'
#' `annotate_ms2()` allows for annotation of mass spectrometry features.
#' Similaritity between query and refrence level 2 spectra are determined via
#' spectral scoring methods. Currently scoring methods `"gnps"` and
#' `"spectral_entropy"` are supported. The scoring method is specified by the
#' `score_params` argument. `score_params` is a list of parameters for the
#' chosen scoring method. Parameters for "gnps" and "spectral_entropy" can be
#' created with notur functions [gnps_params()] and [spec_entropy_params()],
#' respectively.
#'
#'
#' @param query The object generated from `ms2_ms1_compare()`.
#' @param reference A list of reference data downloaded from
#'  \href{https://massdatabase.tidymass.org}{massdatabase}.
#' for more information about this class.
#' @param score_params Parameters for scoring method to be applied.
#' @param precursor_tolerance Precursor mz tolerance. MS2 scans with a
#'  difference in precursor mz less than or equal to this value will be scored.
#' @param min_score Similarity score threshold to determine a match for
#'  annotation. Comparisons with scores below this value will not be reported.
#' @param min_peaks the minimum number of peaks that need to be present before
#' you compare the ms2 spectra.
#' @param cluster_data the cluster object that was generated by `cluster_data()`. 
#' Can also remain NULL if you wish to annotate the data without omu information.
#' @return A `data.frame` with all comparisons with scores above the threshold.
#'  Information for the query scan include `query_ms1_id` (the variable_id
#'  for features in expression_data of the `mass_data` object)
#'  `"query_ms2_id"` (the `ms2_spectrum_id` in the `query`
#'  object), `"query_mz"` (the precursor mz for the scan), and `"query_rt"`
#'  (the retention time for the scan). `query_mz` and `query_rt` are derived
#'  from the ms2 matches data. A column (`"ref_idx`) is included to report the
#'  location for the matching reference molecule in `"reference"`. Scores
#'  are reported in the `"score"` column. Annotation information is returned
#'  given the information provided in the reference used as input.
#'
#' @importFrom stats setNames
#'
#' @usage annotate_ms2(query, reference, score_params,
#' precursor_tolerance, min_score, min_peaks, cluster_data = NULL)
#'
#' @export
annotate_ms2 <- function(query, reference, score_params,
                         precursor_tolerance, min_score, min_peaks = 6, cluster_data = NULL) {
  UseMethod("annotate_ms2", query)
}

#' @rdname annotate_ms2
#' @export
annotate_ms2.mass_data <- function(query, reference, score_params,
  precursor_tolerance, min_score, min_peaks = 6, cluster_data = NULL) {
  ms2 <- query$ms2_matches
  matches <- AnnotateMs2Features(ms2$ms1_compound_id, ms2$ms2_spectrum_id,
                                 ms2$mz, ms2$rt, 
                                 query$peak_data,
                                 reference, score_params, precursor_tolerance,
                                 min_score, min_peaks)

  annotations <- add_annotations(matches, reference)
  if(!is.null(cluster_data)) {
    list_data <- clustur::split_clusters_to_list(cluster_data)
    annotations$OMU <- rep("", times = nrow(annotations))
    annotaion_omus <- lapply(list_data, function(x)  which(annotations$query_ms1_id %in% x))
  
    for(i in seq_along(annotaion_omus)){
      if(length(annotaion_omus[[i]]) <= 0){
        next
      }
      annotations$OMU[annotaion_omus[[i]]] <- names(annotaion_omus[i])
    }                           
  }

  return(annotations)
}

#' @importFrom stats setNames
add_annotations <- function(matches, reference) {

  if(length(reference) <= 0) {
    return()
  }
  ref_info <- data.frame(matrix(ncol = length(reference[[1]]$info$key), nrow = 0))
  names(ref_info) <- reference[[1]]$info$key # Set initial names

  for (ref_idx in matches$ref_idx) {
    new_ann <- stats::setNames(data.frame(t(reference[[ref_idx]]$info$value)),
                               reference[[ref_idx]]$info$key)

    new_ann[setdiff(names(ref_info), names(new_ann))] <- NA
    ref_info[setdiff(names(new_ann), names(ref_info))] <- NA
    ref_info <- rbind(ref_info, new_ann)
  }

  matches <- cbind(matches, ref_info)
  return(matches[order(matches$score, decreasing = T), ])
}


#' @export
#' @title frag
#' @description
#' Clusters the data together
#' @param list_of_mz_int data
#' @param parent_mass data
fragmentation_tree <- function(list_of_mz_int, parent_mass) {
  parent_decomp <- Rdisop::decomposeMass(parent_mass)
  valid_parent_indexes <- which(parent_decomp$valid == "Valid")
  if(length(valid_parent_indexes) == 1) {
    return(parent_decomp$formula[valid_parent_indexes])
  }
  decompList <- vector("list", length(list_of_mz_int$mz))
  for(i in seq_along(list_of_mz_int$mz)){
    if(parent_mass < list_of_mz_int$mz[[i]]){
      next
    }
    decompList[[i]] <- Rdisop::decomposeIsotopes(list_of_mz_int$mz[[i]], list_of_mz_int$intensity[[i]])
  }
  full_data <- c()
  color_count <- 1
  for(i in seq_along(decompList)){
    if(is.null(decompList[[i]])) {
      next
    }
    valid_indexes <- which(decompList[[i]]$valid == "Valid")
    scores <- head(decompList[[i]]$score[valid_indexes], 1000)
    full_data$score <- append(full_data$score, scores)
    full_data$formula <- append(full_data$formula, head(decompList[[i]]$formula[valid_indexes], 1000))
    full_data$color <- c(full_data$color, rep(color_count, length(scores)))
    color_count <- color_count + 1
  }
  scores <- head(parent_decomp$score[valid_parent_indexes], 1000)
  full_data$score <- append(scores, full_data$score)
  full_data$formula <- append(head(parent_decomp$formula[valid_parent_indexes], 1000), full_data$formula)
  full_data$color <- append(rep(0, length(scores)), full_data$color)
  res <- FragmentationTreeTest(full_data, parent_mass, length(unique(full_data$color)))
  if(res == ""){
    return(parent_decomp$formula[[1]])
  }
  return(res)
}


#' @export
#' @title frag
#' @description
#' Clusters the data together
#' @param list_of_mz_int data
#' @param parent_mass data
#' @param num_threads data
fragmentation_tree2 <- function(list_of_mz_int, parent_mass, num_threads = detectCores()/2) {
  parent_decomp <- Rdisop::decomposeMass(parent_mass)
  valid_parent_indexes <- which(parent_decomp$valid == "Valid")
  if(length(valid_parent_indexes) == 1) {
    return(parent_decomp$formula[valid_parent_indexes])
  }
  decompList <- vector("list", length(list_of_mz_int$mz))
  for(i in seq_along(list_of_mz_int$mz)){
    if(parent_mass < list_of_mz_int$mz[[i]]){
      next
    }
    decompList[[i]] <- Rdisop::decomposeIsotopes(list_of_mz_int$mz[[i]], list_of_mz_int$intensity[[i]])
  }
  full_data <- c()
  color_count <- 1
  for(i in seq_along(decompList)){
    if(is.null(decompList[[i]])) {
      next
    }
    valid_indexes <- which(decompList[[i]]$valid == "Valid")
    scores <- head(decompList[[i]]$score[valid_indexes], 1000)
    full_data$score <- append(full_data$score, scores)
    full_data$formula <- append(full_data$formula, head(decompList[[i]]$formula[valid_indexes], 1000))
    full_data$color <- c(full_data$color, rep(color_count, length(scores)))
    color_count <- color_count + 1
  }
  scores <- head(parent_decomp$score[valid_parent_indexes], 1000)
  full_data$score <- append(scores, full_data$score)
  full_data$formula <- append(head(parent_decomp$formula[valid_parent_indexes], 1000), full_data$formula)
  full_data$color <- append(rep(0, length(scores)), full_data$color)
  if(length(full_data$score) <= 0) {
    return(parent_decomp$formula[[1]])
  }
  res <- FragmentationTreeTest2(full_data, parent_mass, num_threads)
  if(res == ""){
    return(parent_decomp$formula[valid_parent_indexes][[1]])
  }
  return(res)
}
