#' Annotate LC-MS/MS features
#' @description
#' Annotate query LC-MS/MS features in a `mass_data` object given a
#' reference list.
#'
#' `annotate_ms2()` allows for annotation of mass spectrometry features.
#' Similarity between query and reference level 2 spectra are determined via
#' spectral scoring methods. Currently scoring methods `"gnps"` and
#' `"spectral_entropy"` are supported. The scoring method is specified by the
#' `score_params` argument. `score_params` is a list of parameters for the
#' chosen scoring method. Parameters for "gnps" and "spectral_entropy" can be
#' created with functions [modified_cosine_params()] and
#' [spec_entropy_params()], respectively. If you are using an hmdb
#' reference database, or a database that does not contain a precursormz
#' please ensure that you expand your ppm to account for the difference.
#'
#'
#' @param mass_data The object generated from `ms2_ms1_compare()`.
#' @param reference Your reference database generated from the
#' `read_msp()` function.
#' We currently only support msp files.
#' @param scoring_params Parameters for scoring method to be applied.
#'  This can be either `modified_cosine_params()` or `spec_entropy_params()`.
#' @param ppm Parts per million. MS2 scans with a
#'  difference in ppm less than or equal to this value will be scored.
#' @param min_score Similarity score threshold to determine a match for
#'  annotation. Comparisons with scores below this value will not be reported.
#' @param chemical_min_score data2
#' @param cluster_data the cluster object that was generated by
#'  `cluster_data()`. Can also remain NULL if you wish to annotate the data
#' without omu information.
#' @param min_peaks the minimum number of peaks that need to be present before
#' you compare the ms2 spectra.
#' @param number_of_threads the number of threads you wish to use for this
#' calculation. Defaults to the number of threads on your computer.
#' @return A `data.frame` with all comparisons with scores above the threshold.
#'  Information for the query scan include `query_ms1_id` (the variable_id
#'  for features in expression_data of the `mass_data` object)
#'  `"query_ms2_id"` (the `ms2_spectrum_id` in the `query`
#'  object), `"query_mz"` (the precursor mz for the scan), and `"query_rt"`
#'  (the retention time for the scan). `query_mz` and `query_rt` are derived
#'  from the ms2 matches data. A column (`"ref_idx`) is included to report the
#'  location for the matching reference molecule in `"reference"`. Scores
#'  are reported in the `"score"` column. `query_formula` and
#' `chemical_similarity`
#'  are also reported. Annotation information is returned
#'  given the information provided in the reference used as input.
#' @examples
#' data <-
#'    import_all_data(peak_table =
#'                    mums2::mums2_example("botryllus_pt_small.csv"),
#'                    meta_data =
#'                    mums2::mums2_example("meta_data_boryillus.csv"),
#'                    format = "None")
#'
#' filtered_data <- data |>
#'    filter_peak_table(filter_mispicked_ions_params()) |>
#'    filter_peak_table(filter_cv_params(cv_threshold = 0.2)) |>
#'    filter_peak_table(filter_group_params(group_threshold = 0.1,
#'                                              "Blanks")) |>
#'    filter_peak_table(filter_insource_ions_params())
#'
#'
#' matched_data <- ms2_ms1_compare(mums2_example("botryllus_v2.gnps.mgf"),
#'  filtered_data, 10, 6)
#'  massbank <- read_msp(mums2_example("MSMS-Neg-Respect.msp"))
#'  annotations <- annotate_ms2(mass_data = matched_data,
#'    reference = massbank, scoring_params = modified_cosine_params(0.5),
#'    ppm = 25,
#'    min_score =  0.5, chemical_min_score = 0)
#'
#' @usage annotate_ms2(mass_data, reference, scoring_params,
#'                     ppm, min_score,
#'                     chemical_min_score,
#'                     cluster_data = NULL, min_peaks = 0,
#'                     number_of_threads = detectCores())
#'
#' @export
#' @return a `data.frame` object containing annotations
annotate_ms2 <- function(mass_data, reference, scoring_params,
                         ppm, min_score,
                         chemical_min_score,
                         cluster_data = NULL, min_peaks = 0,
                         number_of_threads = detectCores()) {

  if (!inherits(mass_data, "mass_data")) {
    stop(paste0("The mass_data object must be created using the",
                " `ms2_ms1_compare()`"))
  }

  if (!inherits(scoring_params, "parameters")) {
    stop(paste0("score_params must be created using the ",
                "`modified_cosine_params()` or `spec_entropy_params()`",
                "function"))
  }

  if (!inherits(cluster_data, "mothur_cluster") && !is.null(cluster_data)) {
    stop(paste0("cluster_data must be created using the `cluster_data()`",
                "function"))
  }

  if (!is.numeric(ppm)) {
    stop("ppm must be numeric")
  }

  if (!is.numeric(min_score)) {
    stop("min_score must be numeric")
  }

  if (!is.numeric(chemical_min_score)) {
    stop("chemical_min_score must be numeric")
  }

  if (!is.numeric(min_peaks)) {
    stop("min_peaks must be numeric")
  }

  if (!is.numeric(number_of_threads)) {
    stop("number_of_threads must be numeric")
  }

  preds <- vector("character", nrow(mass_data$ms2_matches))
  if ("predicted_molecular_formulas" %in% names(mass_data)) {
    preds <- mass_data$predicted_molecular_formulas
  }

  annotations <- AnnotateMs2Features(mass_data$ms2_matches, mass_data$peak_data,
                                     reference, scoring_params, preds, ppm,
                                     min_score, chemical_min_score,
                                     min_peaks, number_of_threads)
  if (nrow(annotations) <= 0) {
    warning("No annotations have been found. Try adjusting your variables.")
    return(annotations)
  }
  cols <- which(!(colnames(annotations) %in% c("query_ms1_id", "query_ms2_id",
                                               "query_mz", "query_rt",
                                               "ref_idx", "query_formula",
                                               "chemical_similarity", "score")))
  annotations <- cbind(annotations[, c("query_ms1_id", "query_ms2_id",
                                       "query_mz", "query_rt", "ref_idx",
                                       "query_formula", "chemical_similarity",
                                       "score")]
                       , annotations[, cols])


  for (i in seq_len(ncol(annotations))){
    annotations[, i] <- trimws(annotations[, i], "right")
  }
  colnames(annotations) <- tolower(colnames(annotations))
  if (is.null(cluster_data)) {
    return(annotations)
  }

  list_data <- clustur::split_clusters_to_list(cluster_data)
  annotations$omu <- rep("", times = nrow(annotations))
  annotation_omus <- lapply(list_data, function(x) {
    which(annotations$query_ms1_id %in% x)
  })

  for (i in seq_along(annotation_omus)){
    if (length(annotation_omus[[i]]) <= 0) {
      next
    }
    annotations$omu[annotation_omus[[i]]] <- names(annotation_omus[i])
  }
  return(annotations)
}
