#' Annotate LC-MS/MS features
#' @description
#' Annotate query LC-MS/MS features in a `mass_data` object given a
#' reference list.
#'
#' `annotate_ms2()` allows for annotation of mass spectrometry features.
#' Similaritity between query and refrence level 2 spectra are determined via
#' spectral scoring methods. Currently scoring methods `"gnps"` and
#' `"spectral_entropy"` are supported. The scoring method is specified by the
#' `score_params` argument. `score_params` is a list of parameters for the
#' chosen scoring method. Parameters for "gnps" and "spectral_entropy" can be
#' created with notur functions [gnps_params()] and [spec_entropy_params()],
#' respectively.
#'
#'
#' @param mass_data The object generated from `ms2_ms1_compare()`.
#' @param reference A list of reference data downloaded from
#'  \href{https://massdatabase.tidymass.org}{massdatabase}.
#' for more information about this class.
#' @param scoring_params Parameters for scoring method to be applied.
#' @param precursor_tolerance Precursor mz tolerance. MS2 scans with a
#'  difference in precursor mz less than or equal to this value will be scored.
#' @param min_score Similarity score threshold to determine a match for
#'  annotation. Comparisons with scores below this value will not be reported.
#' @param chemical_min_score data2
#' @param cluster_data the cluster object that was generated by `cluster_data()`. 
#' Can also remain NULL if you wish to annotate the data without omu information.
#' @param min_peaks the minimum number of peaks that need to be present before
#' you compare the ms2 spectra.
#' @return A `data.frame` with all comparisons with scores above the threshold.
#'  Information for the query scan include `query_ms1_id` (the variable_id
#'  for features in expression_data of the `mass_data` object)
#'  `"query_ms2_id"` (the `ms2_spectrum_id` in the `query`
#'  object), `"query_mz"` (the precursor mz for the scan), and `"query_rt"`
#'  (the retention time for the scan). `query_mz` and `query_rt` are derived
#'  from the ms2 matches data. A column (`"ref_idx`) is included to report the
#'  location for the matching reference molecule in `"reference"`. Scores
#'  are reported in the `"score"` column. Annotation information is returned
#'  given the information provided in the reference used as input.
#'
#' @importFrom stats setNames
#'
#' @usage annotate_ms2(mass_data, reference, scoring_params, 
#'                          precursor_tolerance, min_score, 
#'                          chemical_min_score, cluster_data = NULL, min_peaks = 0)
#'
#' @export
annotate_ms2 <- function(mass_data, reference, scoring_params, 
                           precursor_tolerance, min_score, 
                           chemical_min_score, cluster_data = NULL, min_peaks = 0) {
  UseMethod("annotate_ms2", mass_data)
}

#' @rdname annotate_ms2
#' @export
annotate_ms2.mass_data <- function(mass_data, reference, scoring_params, 
                           precursor_tolerance, min_score, 
                           chemical_min_score, cluster_data = NULL, min_peaks = 0) {
  preds <- vector("character", nrow(mass_data$ms2_matches))
  if("predicted_molecular_formulas" %in% names(mass_data)) {
    preds <- mass_data$predicted_molecular_formulas
  }
  annotations <- AnnotateMs2Features(mass_data$ms2_matches, mass_data$peak_data, reference, scoring_params, 
  preds, precursor_tolerance, min_score, chemical_min_score, min_peaks)

  if(is.null(cluster_data)){
    return(annotations)
  }

  list_data <- clustur::split_clusters_to_list(cluster_data)
  annotations$OMU <- rep("", times = nrow(annotations))
  annotaion_omus <- lapply(list_data, function(x)  which(annotations$query_ms1_id %in% x))

  for(i in seq_along(annotaion_omus)){
    if(length(annotaion_omus[[i]]) <= 0){
      next
    }
    annotations$OMU[annotaion_omus[[i]]] <- names(annotaion_omus[i])
  }                           
  return(annotations)
}