# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AnnotateMs2Features <- function(queryList, querySpectra, annotationController, scoringParameters, formulas, precursorThreshold, minScoreThreshold, chemicalMinScore, minPeaks, threadCount, interactive) {
    .Call(`_mums2_AnnotateMs2Features`, queryList, querySpectra, annotationController, scoringParameters, formulas, precursorThreshold, minScoreThreshold, chemicalMinScore, minPeaks, threadCount, interactive)
}

GetNodeCount <- function(annotationController) {
    .Call(`_mums2_GetNodeCount`, annotationController)
}

GetNode <- function(annotationController, index) {
    .Call(`_mums2_GetNode`, annotationController, index)
}

CombineReferenceDatabases <- function(annotationController, otherAnnotationController) {
    .Call(`_mums2_CombineReferenceDatabases`, annotationController, otherAnnotationController)
}

DeNovoMolecularFormulaPrediction <- function(mzData, masses, ppm, numberOfThreads = 1L, interactive = TRUE) {
    .Call(`_mums2_DeNovoMolecularFormulaPrediction`, mzData, masses, ppm, numberOfThreads, interactive)
}

distMS2 <- function(spectraDataList, parameters, precursor_thresh, cutoff, minPeaks, numberOfThreads, interactive) {
    .Call(`_mums2_distMS2`, spectraDataList, parameters, precursor_thresh, cutoff, minPeaks, numberOfThreads, interactive)
}

CreateCommunityMatrix <- function(communityMatrix) {
    .Call(`_mums2_CreateCommunityMatrix`, communityMatrix)
}

GetCommunityMatrix <- function(communityMatrix) {
    .Call(`_mums2_GetCommunityMatrix`, communityMatrix)
}

RarefactionCalculation <- function(communityMatrix, size, threshold, numberOfThreads, seed = 123L) {
    .Call(`_mums2_RarefactionCalculation`, communityMatrix, size, threshold, numberOfThreads, seed)
}

MeasureBetaDiversity <- function(communityMatrix, index, size, threshold, subsample, numberOfThreads, iterations = 100L, seed = 123L, interactive = TRUE) {
    .Call(`_mums2_MeasureBetaDiversity`, communityMatrix, index, size, threshold, subsample, numberOfThreads, iterations, seed, interactive)
}

MeasureAlphaDiversity <- function(communityMatrix, indexes, size, threshold, subsample, numberOfThreads, iterations = 100L, seed = 123L, interactive = TRUE) {
    .Call(`_mums2_MeasureAlphaDiversity`, communityMatrix, indexes, size, threshold, subsample, numberOfThreads, iterations, seed, interactive)
}

CreateHumanMetabolomicsDB <- function(nodeSize) {
    .Call(`_mums2_CreateHumanMetabolomicsDB`, nodeSize)
}

AddHumanMetabolomicNode <- function(hmdbPtr, names, values, index) {
    invisible(.Call(`_mums2_AddHumanMetabolomicNode`, hmdbPtr, names, values, index))
}

AddSpectra <- function(hmdbPtr, fileNames, databaseNames, interactive) {
    invisible(.Call(`_mums2_AddSpectra`, hmdbPtr, fileNames, databaseNames, interactive))
}

ProcessMs2Files <- function(hmdbPtr, interactive) {
    invisible(.Call(`_mums2_ProcessMs2Files`, hmdbPtr, interactive))
}

CreateAnnotationController <- function(hmdbPtr) {
    .Call(`_mums2_CreateAnnotationController`, hmdbPtr)
}

CompareMS2Ms1 <- function(mz2, mz1, rt2, rt1, mzThreshold, rtThreshold) {
    .Call(`_mums2_CompareMS2Ms1`, mz2, mz1, rt2, rt1, mzThreshold, rtThreshold)
}

CreateProgressBarObject <- function(interactive) {
    .Call(`_mums2_CreateProgressBarObject`, interactive)
}

IncrementProgressBar <- function(progressBar, progress) {
    invisible(.Call(`_mums2_IncrementProgressBar`, progressBar, progress))
}

DestroyProgressBar <- function(progressBar) {
    invisible(.Call(`_mums2_DestroyProgressBar`, progressBar))
}

ReadMgf <- function(path, interactive) {
    .Call(`_mums2_ReadMgf`, path, interactive)
}

ReadMsp <- function(path, interactive) {
    .Call(`_mums2_ReadMsp`, path, interactive)
}

