# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AnnotateMs2Features <- function(variableId, ms2Id, ms2Mz, ms2Rt, ms2Spectra, reference, parameters, precursorThreshold, minScore) {
    .Call(`_mums2_AnnotateMs2Features`, variableId, ms2Id, ms2Mz, ms2Rt, ms2Spectra, reference, parameters, precursorThreshold, minScore)
}

distMS2 <- function(spectraDataList, parameters, precursor_thresh, cutoff) {
    .Call(`_mums2_distMS2`, spectraDataList, parameters, precursor_thresh, cutoff)
}

CalculateDiversity <- function(abundances, diversityIndex) {
    .Call(`_mums2_CalculateDiversity`, abundances, diversityIndex)
}

RarefactionCalculation <- function(communityMatrix, size, threshold) {
    .Call(`_mums2_RarefactionCalculation`, communityMatrix, size, threshold)
}

FasterAvgDist <- function(communityMatrix, index, size, threshold, iterations = 1000L) {
    .Call(`_mums2_FasterAvgDist`, communityMatrix, index, size, threshold, iterations)
}

SomePaper <- function(V, m, weights) {
    .Call(`_mums2_SomePaper`, V, m, weights)
}

Test <- function(samples, weights, sizeToPull, sum) {
    .Call(`_mums2_Test`, samples, weights, sizeToPull, sum)
}

squareRootNormalize <- function(vec) {
    .Call(`_mums2_squareRootNormalize`, vec)
}

scaleNormalize <- function(vec) {
    .Call(`_mums2_scaleNormalize`, vec)
}

ScoreMs2 <- function(name1, mz1, intensity1, precursorMz1, name2, mz2, intensity2, precursorMz2, parameters) {
    .Call(`_mums2_ScoreMs2`, name1, mz1, intensity1, precursorMz1, name2, mz2, intensity2, precursorMz2, parameters)
}

