# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AnnotateMs2Features <- function(variableId, ms2Id, ms2Mz, ms2Rt, ms2Spectra, reference, parameters, precursorThreshold, minScore) {
    .Call(`_mums2_AnnotateMs2Features`, variableId, ms2Id, ms2Mz, ms2Rt, ms2Spectra, reference, parameters, precursorThreshold, minScore)
}

distMS2 <- function(spectraDataList, parameters, precursor_thresh, cutoff) {
    .Call(`_mums2_distMS2`, spectraDataList, parameters, precursor_thresh, cutoff)
}

squareRootNormalize <- function(vec) {
    .Call(`_mums2_squareRootNormalize`, vec)
}

scaleNormalize <- function(vec) {
    .Call(`_mums2_scaleNormalize`, vec)
}

rarefyMs <- function(feature, abund, size, threshold) {
    .Call(`_mums2_rarefyMs`, feature, abund, size, threshold)
}

rarefyMs_2 <- function(feature, abund, size, threshold) {
    .Call(`_mums2_rarefyMs_2`, feature, abund, size, threshold)
}

Test <- function(abund) {
    invisible(.Call(`_mums2_Test`, abund))
}

rarefyMs_3 <- function(feature, abund, size, threshold) {
    .Call(`_mums2_rarefyMs_3`, feature, abund, size, threshold)
}

CalculateAlphaDiverstiy <- function(feature, abund, size, threshold, iterations = 1000L) {
    .Call(`_mums2_CalculateAlphaDiverstiy`, feature, abund, size, threshold, iterations)
}

CalculateAlphaDiversityInt <- function(feature, abund, size, threshold, iterations = 1000L) {
    .Call(`_mums2_CalculateAlphaDiversityInt`, feature, abund, size, threshold, iterations)
}

CalculateAlphaDiversityShannon <- function(feature, abund, size, threshold, iterations = 1000L) {
    .Call(`_mums2_CalculateAlphaDiversityShannon`, feature, abund, size, threshold, iterations)
}

ScoreMs2 <- function(name1, mz1, intensity1, precursorMz1, name2, mz2, intensity2, precursorMz2, parameters) {
    .Call(`_mums2_ScoreMs2`, name1, mz1, intensity1, precursorMz1, name2, mz2, intensity2, precursorMz2, parameters)
}

